# -*- coding: utf-8 -*-
"""RAGWomenMentalHealth.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CemlOUns3Cr5mDUhtgxAH_7M4qPNbOv_
"""

#Installing the required libraries for LLMs, RAG, and document parsing
!pip install -q torch transformers accelerate bitsandbytes
!pip install -q sentence-transformers rank-bm25 chromadb faiss-cpu
!pip install -q langchain langchain-community langchain-huggingface
!pip install -q pydantic pymupdf
!pip install -q langchain-classic

#Adding libraries and function
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, BitsAndBytesConfig, pipeline
from langchain_huggingface import HuggingFacePipeline, HuggingFaceEmbeddings
from langchain_community.document_loaders import PyMuPDFLoader
from langchain_text_splitters import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import Chroma
from langchain_classic.chains import create_history_aware_retriever, create_retrieval_chain
from langchain_classic.chains.combine_documents import create_stuff_documents_chain
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.messages import HumanMessage, AIMessage
import os


print("Loading Qwen2.5-7B-Instruct in 4-bit")
model_name = "Qwen/Qwen2.5-7B-Instruct"

# 4-bit quantization config to compress the model to ~5GB of VRAM (Needed for saving memory)
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_compute_dtype=torch.float16
)

# Load the tokenizer and the model
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    device_map="auto",
    torch_dtype=torch.float16,
    quantization_config=quantization_config,
)

# Create a text-generation pipeline
hf_pipeline = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    max_new_tokens=512,       #Example for maximum number of chatbot response
    temperature=0.1,          #Low temperature for minimal hallucination
    repetition_penalty=1.1,
    return_full_text=False
)

#Connecting to LangChain's LLM interface
llm = HuggingFacePipeline(pipeline=hf_pipeline)
print("Model loaded successfully!")

print("Setting up Embeddings...")
#Downloading the Sentence Transformers model for creating embeddings
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")
#Example of a pdf text that will be used in a model

--------------------------------------------------------
dummy_text = """
The menstrual cycle can significantly impact mental health. Premenstrual Syndrome (PMS) encompasses physical and emotional symptoms, including fatigue, sleep disruption, and mild anxiety.
Premenstrual Dysphoric Disorder (PMDD) is a severe form of PMS characterized by significant depression, anxiety, and irritability that can impair daily functioning.
Sleep hygiene, such as maintaining a regular sleep schedule, can alleviate some fatigue. Supplements like Magnesium and Vitamin B6 have been studied for premenstrual symptoms, but should be discussed with a doctor as they can interact with medications.
If someone experiences severe hopelessness or suicidal ideation, immediate crisis support is required.
"""
with open("sample_mental_health_doc.txt", "w") as f:
    f.write(dummy_text)

from langchain_community.document_loaders import TextLoader
loader = TextLoader("sample_mental_health_doc.txt")
docs = loader.load()
# ---------------------------------------------------------

#Spliting the document into chunks of 300 characters, with 50 overlap
text_splitter = RecursiveCharacterTextSplitter(chunk_size=300, chunk_overlap=50)
splits = text_splitter.split_documents(docs)

#Storing the embeddings in a Chroma vector database
vectorstore = Chroma.from_documents(documents=splits, embedding=embeddings)

#Creating a retriever to fetch the top 3 most relevant chunks
retriever = vectorstore.as_retriever(search_kwargs={"k": 3})
print("Vector database created with documents!")

!pip install -q pydantic pymupdf docx2txt unstructured
print("Setting up Embeddings...")
# Download the Sentence Transformers model for creating embeddings
embeddings = HuggingFaceEmbeddings(model_name="sentence-transformers/all-MiniLM-L6-v2")

#Directory of documents
folder_path = "my_documents"
os.makedirs(folder_path, exist_ok=True)

docs = []
valid_files_found = 0

print(f"Scanning the '{folder_path}' folder for documents...")

#Going through different file formats
for filename in os.listdir(folder_path):
    filepath = os.path.join(folder_path, filename)

    try:
        if filename.endswith(".pdf"):
            print(f"Loading PDF: {filename}")
            loader = PyMuPDFLoader(filepath)
            docs.extend(loader.load())
            valid_files_found += 1

        elif filename.endswith(".docx"):
            print(f"Loading Word Doc: {filename}")
            loader = Docx2txtLoader(filepath)
            docs.extend(loader.load())
            valid_files_found += 1

        elif filename.endswith(".epub"):
            print(f"Loading EPUB: {filename}")
            loader = UnstructuredEPubLoader(filepath)
            docs.extend(loader.load())
            valid_files_found += 1

        elif filename.endswith(".txt"):
            print(f"Loading Text File: {filename}")
            loader = TextLoader(filepath)
            docs.extend(loader.load())
            valid_files_found += 1

    except Exception as e:
        print(f"Error loading {filename}: {e}")

if valid_files_found == 0:
    print("\n⚠️ WARNING: No valid files (.pdf, .docx, .txt) found in the 'my_documents' folder!")
    print("Please upload your research files to the folder and run this cell again.")
else:
    print(f"\nSuccessfully loaded {len(docs)} total pages/sections from your documents.")

    # Chunk the massive text into 500-character blocks with 50-character overlap
    print("Splitting documents into searchable chunks (this may take a moment for large files)...")
    text_splitter = RecursiveCharacterTextSplitter(chunk_size=500, chunk_overlap=50)
    splits = text_splitter.split_documents(docs)
    print(f"Created {len(splits)} individual chunks.")

    # Store embeddings in a PERSISTENT Chroma vector database
    # By saving to "./chroma_db", you won't have to re-process these big files if Colab disconnects!
    print("Embedding chunks and saving to Vector Database...")
    vectorstore = Chroma.from_documents(
        documents=splits,
        embedding=embeddings,
        persist_directory="./chroma_db"
    )

    # Create a retriever to fetch the top 5 most relevant chunks (increased for larger datasets)
    retriever = vectorstore.as_retriever(search_kwargs={"k": 5})
    print("✅ Vector database created and saved to disk!")

# 1. History-Aware Prompt
#Rewrites follow-up questions so they become stand alone individual questions
contextualize_q_system_prompt = """Given a chat history and the latest user question \
which might reference context in the chat history, formulate a standalone question \
which can be understood without the chat history. Do NOT answer the question, \
just reformulate it if needed and otherwise return it as is."""

contextualize_q_prompt = ChatPromptTemplate.from_messages([
    ("system", contextualize_q_system_prompt),
    MessagesPlaceholder("chat_history"),
    ("human", "{input}"),
])

history_aware_retriever = create_history_aware_retriever(
    llm, retriever, contextualize_q_prompt
)

# 2. Main Q&A Prompt
# Enforces the "Educational System, Not Medical Diagnosis" rule from your thesis
qa_system_prompt = """You are an educational chatbot focused on women's mental and hormonal health.
You are NOT a doctor, therapist, or emergency service.
Use the following retrieved context to explain possible patterns, encourage tracking, and suggest discussing symptoms with a healthcare professional when appropriate.
Use language such as 'possible explanations include' rather than 'you have'.
If you don't know the answer based on the context, say so clearly.

Context:
{context}"""

#qa_system_prompt= "You are a medical summarizer. Answer the user's question using ONLY the information explicitly stated in the provided context. Do not add any outside knowledge. If the exact answer is not in the context, say 'I do not have that information. Context: {context}'"
qa_prompt = ChatPromptTemplate.from_messages([
    ("system", qa_system_prompt),
    MessagesPlaceholder("chat_history"),
    ("human", "{input}"),
])

# Combine everything into the final RAG chain
question_answer_chain = create_stuff_documents_chain(llm, qa_prompt)
rag_chain = create_retrieval_chain(history_aware_retriever, question_answer_chain)
print("Conversational RAG Chain initialized!")

chat_history = []
print("=== Women's Health Educational Bot ===")
print("Type your questions below. Type 'quit' to exit.\n")

while True:
    user_input = input("You: ")
    if user_input.lower() in ["quit", "exit"]:
        print("Ending chat. Goodbye!")
        break

    # Run the chain
    response = rag_chain.invoke({"input": user_input, "chat_history": chat_history})
    bot_answer = response["answer"]

    print(f"\nBot: {bot_answer}\n")
    print("-" * 50)

    # Save the interaction to memory
    chat_history.extend([
        HumanMessage(content=user_input),
        AIMessage(content=bot_answer)
    ])